//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichChieu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LichChieu()
        {
            this.Ves = new HashSet<Ve>();
        }
    
        public string IDLichChieu { get; set; }
        public Nullable<System.DateTime> ThoiGianChieu { get; set; }
        public string IDPhong { get; set; }
        public string IDDinhDang { get; set; }
        public string GiaVe { get; set; }
        public string TrangThai { get; set; }
    
        public virtual DinhDangPhim DinhDangPhim { get; set; }
        public virtual PhongChieu PhongChieu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ve> Ves { get; set; }
    }
}
