//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Phim()
        {
            this.DinhDangPhims = new HashSet<DinhDangPhim>();
        }
    
        public string IDPhim { get; set; }
        public string TenPhim { get; set; }
        public Nullable<double> ThoiLuong { get; set; }
        public Nullable<System.DateTime> NgayKhoiChieu { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public string SanXuat { get; set; }
        public string DaoDien { get; set; }
        public Nullable<int> NamSX { get; set; }
        public string IDTheLoai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DinhDangPhim> DinhDangPhims { get; set; }
        public virtual TheLoai TheLoai { get; set; }
    }
}
